### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by yasserelsaid** [trotzig/react-available-times#52]
I am using next.js to for my React app and I am getting this error

`ReferenceError: window is not defined
    at C:\Users\yasserelsaid\Desktop\rmc\node_modules\react-available-times\dist\main.js:196:3
    at C:\Users\yasserelsaid\Desktop\rmc\node_modules\react-available-times\dist\main.js:186:47
    at module.exports.module.exports (C:\Users\yasserelsaid\Desktop\rmc\node_modules\react-available-times\dist\main.js:224:68)
    at Object.<anonymous> (C:\Users\yasserelsaid\Desktop\rmc\node_modules\react-available-times\dist\main.js:5432:36)
    at __webpack_require__ (C:\Users\yasserelsaid\Desktop\rmc\node_modules\react-available-times\dist\main.js:21:30)
    at Object.<anonymous> (C:\Users\yasserelsaid\Desktop\rmc\node_modules\react-available-times\dist\main.js:1181:25)
    at __webpack_require__ (C:\Users\yasserelsaid\Desktop\rmc\node_modules\react-available-times\dist\main.js:21:30)
    at Object.<anonymous> (C:\Users\yasserelsaid\Desktop\rmc\node_modules\react-available-times\dist\main.js:695:25)
    at __webpack_require__ (C:\Users\yasserelsaid\Desktop\rmc\node_modules\react-available-times\dist\main.js:21:30)
    at Object.<anonymous> (C:\Users\yasserelsaid\Desktop\rmc\node_modules\react-available-times\dist\main.js:3190:18)
    at __webpack_require__ (C:\Users\yasserelsaid\Desktop\rmc\node_modules\react-available-times\dist\main.js:21:30)
    at C:\Users\yasserelsaid\Desktop\rmc\node_modules\react-available-times\dist\main.js:67:18
    at Object.<anonymous> (C:\Users\yasserelsaid\Desktop\rmc\node_modules\react-available-times\dist\main.js:70:10)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)`

**Comment by ecenuratasayar** [comment]
you can handle that problem with ;

let AvailableTimes = null

if (typeof window !== 'undefined') {
  AvailableTimes = require('react-available-times')
}
